version: '3.7'
services:
  eureka:
    build: Eureka/.
    ports:
      - "8761:8761"
    networks:
      - Hygge
  article-server:
    build: Article-Server/.
    ports:
      - "8082:8081"
    volumes:
      - /home/log/:/logFile
    depends_on:
      - eureka
    links:
      - "eureka:eureka"
    expose:
      - "8081"
    networks:
      Hygge:
        ipv4_address: 172.19.0.8
  user-server:
    build: User-Server/.
    ports:
      - "8081:8080"
    volumes:
      - /home/log/:/logFile
    depends_on:
      - eureka
    links:
      - "eureka:eureka"
    expose:
      - "8080"
    networks:
      Hygge:
        ipv4_address: 172.19.0.9
networks:
  Hygge:
    external: true
    name: Hygge